CREATE ROLE hotel_admin LOGIN PASSWORD 'hotel';
GRANT ALL PRIVILEGES ON DATABASE hotel TO hotel_admin;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO hotel_admin;
GRANT ALL PRIVILEGES ON ALL SEQUENCES IN SCHEMA public TO hotel_admin;
GRANT ALL PRIVILEGES ON SCHEMA public TO hotel_admin;